### PR TITLE
Step 1 Updates

### PR DESCRIPTION
**Pull request by araman-io**
hello Vertx maintainers.

My name is Anand and I recently started playing with Vertx. Thanks for the excellent documentation which served me well as made my way through the vertx java guide (wiki). 

I did run into a few issues
* the guide is based on v3.x whereas you just released v4.2
* some of the APIs are deprecated e.g. JDBCClient
* Relies heavily on callbacks. This may have been a good reason for v3 but since V4 has moved to `Promise` and `Future` they may be a better concept to begin with and learn

While I was able to resolve most of the issues by referring to the official docs, I fear others may abandon their learning journey. 

I would like to help with updating the guide to version 4. This pull request is the refactored `step 1`. If you are ok I am happy to spend more time and work through the guide update it in my spare time. If you guys are happy we can discuss the process offline (one PR per step or one consolidated PR).

Do let me know if this is something which will be of use and benefit the larger vertx community

Thanks
anand
araman@gmail.com

### CODE REVIEW

**Comment by tsegismont** [comment]
@araman-io hi, thanks for reaching out. We do not plan to maintain this guide going forward. We should have made it clear in the `README` file.

@jponge @vietj do you have any preference for the wording or shall I go ahead and update it? Perhaps we should also archive the project (in the GH sense).

**Comment by jponge** [comment]
> @jponge <https://github.com/jponge> @vietj <https://github.com/vietj> do you have any preference for the wording or shall I go ahead and update it? Perhaps we should also archive the project (in the GH sense).
> 
> 

I’m in favour of updating the README (I trust you’ll have it right!) and archiving the GH repo 👍

**Comment by jponge** [comment]
And many thanks @araman-io for the contribution, but we decided not to maintain this, especially as some modules are not what we're advocating moving forward (e.g., JDBC, Shiro Auth, etc).

That being said this is fully open source, so feel-free to fork it if you feel like doing so.

**Comment by ghost** [comment]
@jponge thanks for the additional context. Helps me understand the decision. I will fork it and create a smaller version for v4.2. 

Out of curiosity what are we recommending others to use instead of vertx-jdbc-client.

thanks
anand

**Comment by tsegismont** [comment]
Closing, see #97 

@vietj I am not granted to archive this project

**Comment by jponge** [comment]
We recommend using the new Vertx SQL client and the proper reactive driver implementations we provide (Pg, MySQL, etc)

**Pull request closed without merging**
